name: tests
on: [push, pull_request]

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies & run tests
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt
          PYTHONPATH=. pytest -q

